<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Marilo.Demo</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Marilo.Core\Marilo.Core.csproj" />
    <ProjectReference Include="..\..\src\Marilo.Components\Marilo.Components.csproj" />
    <ProjectReference Include="..\..\src\Marilo.Icons\Marilo.Icons.csproj" />
    <ProjectReference Include="..\..\src\Marilo.Providers.FluentUI\Marilo.Providers.FluentUI.csproj" />
    <ProjectReference Include="..\..\src\Marilo.Providers.Bootstrap\Marilo.Providers.Bootstrap.csproj" />
  </ItemGroup>

</Project>
