<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <PackageId>Marilo.Components</PackageId>
    <Version>2.0.0</Version>
    <Description>Style-agnostic Blazor components for the Marilo component library</Description>
    <PackageTags>blazor;components;razor-class-library;ui-framework</PackageTags>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Marilo.Core\Marilo.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Marilo.Tests.Unit" />
  </ItemGroup>

</Project>
