import { type Page } from '@playwright/test';
import { type ThemeConfig } from '../config/themes';
import { type ComponentEntry } from '../config/component-registry';

/**
 * Wait for Blazor Server to finish its initial render cycle.
 * Blazor Server uses SignalR, so the page may briefly show a loading state
 * before the interactive content appears.
 */
export async function waitForBlazorReady(page: Page): Promise<void> {
  // Wait for the app-root to be visible (hidden until settings load)
  await page.waitForSelector('.app-root:not([style*="visibility:hidden"])', {
    timeout: 15_000,
  });
  // Give Blazor a beat to finish rendering after the root appears
  await page.waitForTimeout(500);
}

/**
 * Apply a theme (provider + light/dark mode) to the demo app.
 *
 * The demo app stores preferences in localStorage and reloads on provider change.
 * This function sets localStorage directly, then navigates to trigger the reload
 * with the correct theme already applied.
 *
 * @param page - Playwright page
 * @param theme - Theme configuration to apply
 * @param route - Route to navigate to after applying theme
 */
export async function applyTheme(
  page: Page,
  theme: ThemeConfig,
  route: string,
): Promise<void> {
  // Set localStorage before navigation so the page loads with correct theme
  await page.addInitScript(({ provider, darkMode }) => {
    localStorage.setItem('marilo:provider', provider);
    localStorage.setItem('marilo:darkmode', darkMode);
  }, {
    provider: theme.provider,
    darkMode: theme.mode === 'dark' ? '1' : '0',
  });

  await page.goto(route, { waitUntil: 'networkidle' });
  await waitForBlazorReady(page);
}

/**
 * Navigate to a component demo page with the specified theme applied.
 * This is the primary entry point for visual parity test setup.
 *
 * @param page - Playwright page
 * @param component - Component registry entry
 * @param theme - Theme to apply
 */
export async function openComponentPage(
  page: Page,
  component: ComponentEntry,
  theme: ThemeConfig,
): Promise<void> {
  await applyTheme(page, theme, component.route);
}

/**
 * Scroll to a specific DemoSection by its title anchor.
 *
 * The demo app generates anchor IDs via PageSectionTracker.ToAnchorId():
 *   title.ToLowerInvariant().Replace(' ', '-').Replace("(","").Replace(")","").Replace("&","").Replace("'","")
 *
 * This function replicates that exact logic.
 *
 * @param page - Playwright page
 * @param sectionTitle - The DemoSection title to scroll to
 */
export async function scrollToDemoSection(
  page: Page,
  sectionTitle: string,
): Promise<void> {
  const anchorId = toAnchorId(sectionTitle);

  const section = page.locator(`#${cssEscape(anchorId)}`);
  if (await section.count() > 0) {
    await section.scrollIntoViewIfNeeded();
    await page.waitForTimeout(300); // Let scroll settle
  }
}

/**
 * Locate the first instance of a component on the page by its root selector.
 * Returns the Playwright locator for element-level screenshots.
 */
export function locateComponent(page: Page, component: ComponentEntry) {
  return page.locator(component.rootSelector).first();
}

/**
 * Locate a specific demo section's preview content.
 * Useful when a page has multiple instances of the same component and
 * you need to target a specific demo scenario.
 *
 * @param page - Playwright page
 * @param sectionTitle - Title of the DemoSection to target
 */
export function locateDemoPreview(page: Page, sectionTitle: string) {
  const anchorId = toAnchorId(sectionTitle);
  return page.locator(`#${cssEscape(anchorId)} .demo-panel-preview`);
}

/**
 * Replicate the C# PageSectionTracker.ToAnchorId() logic exactly:
 *   title.ToLowerInvariant().Replace(' ', '-').Replace("(","").Replace(")","").Replace("&","").Replace("'","")
 */
export function toAnchorId(title: string): string {
  return title
    .toLowerCase()
    .replace(/ /g, '-')
    .replace(/[()&']/g, '');
}

/**
 * Escape a string for use in a CSS selector (Node.js-compatible).
 * CSS.escape() is browser-only; this covers the characters that can
 * appear in anchor IDs generated by toAnchorId().
 */
export function cssEscape(value: string): string {
  return value.replace(/([^\w-])/g, '\\$1');
}
